version: '3.8'

services:
  postgres_consult:
    image: postgres
    container_name: postgres_consult
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_consult:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - network_consult
    restart: unless-stopped

  pgadmin_consult:
    image: dpage/pgadmin4
    container_name: pgadmin_consult
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "15434:80"
    networks:
      - network_consult
    restart: unless-stopped

  node_consult:
    build: .
    container_name: node_consult
    volumes:
      - .:/usr/app
    ports:
      - "3335:3335"
    networks:
      - network_consult
    restart: unless-stopped

networks:
  network_consult:

volumes:
  postgres_data_consult:
