services:
  node_consult:
    build: .
    container_name: node_consult
    ports:
      - "4000:4000"
    networks:
      - backend_network_core_note
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_corelab:5432/${POSTGRES_DB}"
    restart: unless-stopped
    entrypoint: ["/usr/src/clinica/entrypoint.sh"]

networks:
  backend_network_core_note:
    external: true
